model_list:
  # Local Models on Modal
  - model_name: "base-gemma"
    litellm_params:
      model: "ollama/gemma3:1b"
      api_base: "https://gcet--ollama-base-model-ollamabase-serve.modal.run"
  - model_name: "medium-mistral"
    litellm_params:
      model: "ollama/mistral:7b"
      api_base: "https://gcet--ollama-medium-model-ollamamedium-serve.modal.run"
  - model_name: "deep-qwen"
    litellm_params:
      model: "ollama/qwen3.5:9b"
      api_base: "https://gcet--ollama-deep-model-ollamadeep-serve.modal.run"

  # Mistral Cloud Models
  - model_name: "open-mistral-nemo"
    litellm_params:
      model: "mistral/open-mistral-nemo"
      api_key: "yU15nPBcRPH0myzxjlZBQATOvDBRSgQB"

  - model_name: "mistral-small-latest"
    litellm_params:
      model: "mistral/mistral-small-latest"
      api_key: "yU15nPBcRPH0myzxjlZBQATOvDBRSgQB"

  - model_name: "mistral-large-latest"
    litellm_params:
      model: "mistral/mistral-large-latest"
      api_key: "yU15nPBcRPH0myzxjlZBQATOvDBRSgQB"

router_settings:
  routing_strategy: "least-busy"
  num_retries: 2
  timeout: 12000